export enum Category{
    BEVERAGES = 'BEVERAGES',
	BREAD = 'BREAD',
	CEREAL = 'CEREAL',
	CONDIMENTS = 'CONDIMENTS',
	CONFECTIONERY = 'CONFECTIONERY',
	CANNEDGOODS = 'CANNEDGOODS',
	DAIRY = 'DAIRY',
	EGGS = 'EGGS',
	CHEESE = 'CHEESE',
	FRUITS = 'FRUITS',
	VEGETABLES = 'VEGETABLES',
	PASTA = 'PASTA',
	GRAINS = 'GRAINS',
	MEAT = 'MEAT',
	SEAFOOD = 'SEAFOOD',
	PERSONALCARE = 'PERSONALCARE',
	CLEANINIGSUPPLIES = 'CLEANINIGSUPPLIES',
	MISCELLANEOUS = 'MISCELLANEOUS'
	
}